import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const greycliff = localFont({
  src: [
    { path: "../assets/fonts/ConnaryFagen-GreycliffCFExtraLight.otf", weight: "200", style: "normal" },
    { path: "../assets/fonts/ConnaryFagen-GreycliffCFRegular.otf",     weight: "400", style: "normal" },
    { path: "../assets/fonts/ConnaryFagen-GreycliffCFBold.otf",        weight: "700", style: "normal" },
    { path: "../assets/fonts/ConnaryFagen-GreycliffCFHeavy.otf",       weight: "800", style: "normal" },
  ],
  display: "swap",
  variable: "--font-greycliff",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sv" className={greycliff.variable}>
      <body
        className={`${greycliff.className} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
